### ISSUE TITLE
Error in TwistedSNMP!

### ISSUE THREAD

**Issue by MDTech-us-MAN** [oftc/oftc-ircservices#7]
Hello,

I cannot start the server because I get the following error:
```
# /etc/init.d/oftcdns start                    Starting OFTCDNS daemon: oftcdnsUnhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "/usr/local/lib/oftcdns/oftcdns.tac", line 20, in <module>
    from twistedsnmp import agent, agentprotocol, bisectoidstore
  File "/usr/local/lib/python2.7/dist-packages/twistedsnmp/agent.py", line 4, in <module>
    from twistedsnmp import datatypes
  File "/usr/local/lib/python2.7/dist-packages/twistedsnmp/datatypes.py", line 9, in <module>
    from twistedsnmp.pysnmpproto import v2c,v1,rfc1902
exceptions.ImportError: cannot import name v2c

Failed to load application: cannot import name v2c
```

I am using Ubuntu Server 14.04.1

**Comment by ChristophBerg** [comment]
oftcdns is being decommissioned, so I'm closing this bug now.
